#!/bin/bash

function count-line {
	count=0
	while read line
	do
		if ! [ -z "$line" ] 
		then
		count=$(( count + 1 ))
		fi
	done < $1
	echo $count
}

function open { # функция для прохода по файлам папки
	cnt=0
	for file in $1/* # проходим по всем файлам и папкам
	do
		case $file in
			*.c | *.h) # если .c или .h файл то увеличиваем счетчик
				cnt=$(( $cnt + $( count-line $file ) )) ;;
			*)
				if [ -d $file ] # если папка то идем в нее
				then
					cnt=$(( $cnt + $(open $file) ))
				fi ;;
			esac

	done
	echo $cnt

}

if ! [ $# -eq 1 ] # если количество аргументов неправильное, то просим ввести по шаблону
then
	echo "try ./line-counter name-directory"
elif ! [ -e $1 ] # если имя введено неправильно, то говорим, что такой папки нет
then
	echo "there is no such directory"
else
	res=$( open $1 )
	echo $res
fi

